
import { GoogleGenAI, Type, GenerateContentResponse, Modality } from "@google/genai";

const SYSTEM_INSTRUCTION = 'You are Srimanyu, a premium, world-class AI assistant. You are eloquent, precise, and highly capable. Always cite your sources when using search data.';

// Helper to check for permission/access errors in various formats
const isAuthError = (error: any) => {
  try {
    // Check specific object properties often returned by Google GenAI SDK
    if (error.status === 403 || error.status === 'PERMISSION_DENIED') return true;
    if (error.code === 403) return true;

    const msg = (error.message || '').toLowerCase();
    if (msg.includes('permission denied') || msg.includes('403') || msg.includes('caller does not have permission')) return true;

    const str = JSON.stringify(error).toLowerCase();
    return str.includes('permission_denied') || str.includes('"code":403') || str.includes('caller does not have permission');
  } catch (e) {
    // If we can't inspect the error, assume it might be auth if it looks like a fetch failure
    return false;
  }
};

const extractImage = (response: GenerateContentResponse) => {
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }
  throw new Error("No image generated by Srimanyu Vision.");
};

export const generateText = async (prompt: string) => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

  try {
    // Attempt 1: Premium Model + Google Search (Most liable to 403)
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: prompt,
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        tools: [{ googleSearch: {} }]
      }
    });
    
    return {
      text: response.text,
      sources: response.candidates?.[0]?.groundingMetadata?.groundingChunks?.map((chunk: any) => ({
        title: chunk.web?.title || 'Source',
        url: chunk.web?.uri
      })).filter((s: any) => s.url) || []
    };
  } catch (error: any) {
    if (isAuthError(error)) {
      console.warn("Primary generation failed (403), attempting Flash fallback...");
      try {
        // Attempt 2: Flash Model 3.0 (High availability, no tools)
        const response = await ai.models.generateContent({
          model: 'gemini-3-flash-preview',
          contents: prompt,
          config: {
            systemInstruction: SYSTEM_INSTRUCTION
          }
        });
        return { text: response.text, sources: [] };
      } catch (retryError) {
         if (isAuthError(retryError)) {
            console.warn("Secondary generation failed (403), attempting 2.0 Flash fallback...");
            // Attempt 3: Flash Model 2.0 (Last resort for permissions)
            const response = await ai.models.generateContent({
              model: 'gemini-2.0-flash-exp',
              contents: prompt,
              config: {
                systemInstruction: SYSTEM_INSTRUCTION
              }
            });
            return { text: response.text, sources: [] };
         }
         throw retryError;
      }
    }
    throw error;
  }
};

export const generateSpeech = async (text: string) => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  const response = await ai.models.generateContent({
    model: "gemini-2.5-flash-preview-tts",
    contents: [{ parts: [{ text: `Speak in a professional, calm, premium male voice: ${text.substring(0, 500)}` }] }],
    config: {
      responseModalities: [Modality.AUDIO],
      speechConfig: {
        voiceConfig: {
          prebuiltVoiceConfig: { voiceName: 'Kore' },
        },
      },
    },
  });

  const base64Audio = response.candidates?.[0]?.content?.parts?.[0]?.inlineData?.data;
  if (!base64Audio) throw new Error("Vocal synthesis failed");
  return base64Audio;
};

export const generateImage = async (prompt: string) => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  try {
    // Attempt 1: Premium Image Model (1K, Requires specific permissions)
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [{ text: prompt }]
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
          imageSize: "1K"
        }
      }
    });
    return extractImage(response);
  } catch (error: any) {
    if (isAuthError(error)) {
      console.warn("Pro image generation failed, attempting standard fallback...");
      // Attempt 2: Standard Image Model (No imageSize config allowed)
      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [{ text: prompt }]
        },
        config: {
          imageConfig: {
            aspectRatio: "1:1"
          }
        }
      });
      return extractImage(response);
    }
    throw error;
  }
};

export const generateVideo = async (prompt: string) => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  try {
    let operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt: prompt,
        config: {
        numberOfVideos: 1,
        resolution: '720p',
        aspectRatio: '16:9'
        }
    });

    while (!operation.done) {
        await new Promise(resolve => setTimeout(resolve, 8000));
        operation = await ai.operations.getVideosOperation({ operation: operation });
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) throw new Error("Video synthesis timed out.");
    
    const response = await fetch(`${downloadLink}&key=${process.env.API_KEY}`);
    const blob = await response.blob();
    return URL.createObjectURL(blob);
  } catch (error: any) {
    if (isAuthError(error)) {
        throw new Error("Video generation requires a Paid or Trusted Tester API Key. Your current key does not have permission for Veo models.");
    }
    throw error;
  }
};

export const createProject = async (description: string) => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  
  const schema = {
    type: Type.OBJECT,
    properties: {
      name: { type: Type.STRING },
      description: { type: Type.STRING },
      files: {
        type: Type.ARRAY,
        items: {
          type: Type.OBJECT,
          properties: {
            name: { type: Type.STRING },
            content: { type: Type.STRING },
            language: { type: Type.STRING }
          },
          required: ["name", "content", "language"]
        }
      }
    },
    required: ["name", "description", "files"]
  };

  const promptContent = `Create a professional coding project structure based on: ${description}. 
               Return a JSON object with "name", "description", and an array of "files" 
               where each file has "name", "content", and "language".`;

  try {
    // Attempt 1: Pro Model
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-preview',
      contents: promptContent,
      config: {
        responseMimeType: "application/json",
        responseSchema: schema
      }
    });
    return JSON.parse(response.text || '{}');
  } catch (error: any) {
    if (isAuthError(error)) {
        console.warn("Pro project generation failed, attempting Flash fallback...");
        // Attempt 2: Flash Model
        const response = await ai.models.generateContent({
          model: 'gemini-3-flash-preview',
          contents: promptContent,
          config: {
            responseMimeType: "application/json",
            responseSchema: schema
          }
        });
        return JSON.parse(response.text || '{}');
    }
    throw error;
  }
};
